import { AUDIT_EVENT_TYPES, type Result } from '@rolepay/core'
import type {
  AuditEventView,
  AuditPort,
  AuditQuery,
  PolicyActor,
  PolicyDetail,
  PolicyDraft,
  PolicyError,
  PolicyMode,
  PolicyPort,
  PolicyPreview,
  PolicySummary,
  PolicyVersionView,
  RunOrigin,
  ScheduledRunView,
} from '../dashboard/policyPort.js'

type Stored = { guildId: string; detail: PolicyDetail; versions: PolicyVersionView[]; preview: PolicyPreview | null }
type Ref = { guildId: string; policyId: string }

const ok = <T>(value: T): Result<T, PolicyError> => ({ ok: true, value })
const fail = (code: string, message?: string): Result<never, PolicyError> => ({ ok: false, error: message ? { code, message } : { code } })

const DAILY_REFUSED = 'A daily schedule is a testnet demo control, off on this server: choose weekly or monthly.'

/** The shortest veto window core allows without the demo controls, in minutes. */
const MIN_VETO_MINUTES = 60
const MAX_VETO_MINUTES = 7 * 24 * 60

/**
 * The policy and audit ports in memory, for the dashboard's page tests and the browser e2e of the
 * pages alone. It behaves the way core does, and the page contract (`@rolepay/web/contract`)
 * holds the two equal: the approver role is re-checked from the actor's roles on every action
 * (`not_permitted`); an instruction is "compiled" once into a draft (one containing "unclear"
 * cannot be compiled); an edit makes a new version, in force at once on a policy approved before
 * (only the approver role acts here; the policy keeps running and its mode unless the edit names
 * one), or, with a separate approver required (`setSeparateApprover`) or on a draft, putting the
 * policy back to draft (it stops running and autopilot is switched off) until that version is
 * approved; discarding an edit goes back to the last approved version, paused; every action lands
 * in the audit stream. `calls` records every action with its actor.
 */
export class InMemoryPolicies implements PolicyPort, AuditPort {
  readonly eventTypes: readonly string[] = AUDIT_EVENT_TYPES
  /** Like core with the testnet demo controls on: daily schedules allowed. Off by default, as in production. */
  dailySchedules = false
  readonly calls: { method: string; guildId: string; policyId?: string; actor: PolicyActor }[] = []
  private readonly policies = new Map<string, Stored>()
  private readonly stream: (AuditEventView & { guildId: string })[] = []
  private readonly origins = new Map<string, RunOrigin>()
  private readonly approverRoles = new Map<string, string>()
  private readonly separateApprover = new Set<string>()
  private counter = 0

  constructor(private readonly clock: { now(): Date } = { now: () => new Date() }) {}

  // ---- seeding (tests) ---------------------------------------------------------------------

  /** The role that may act in this guild, as core reads it from the community. */
  setApproverRole(guildId: string, roleId: string) {
    this.approverRoles.set(guildId, roleId)
  }

  /** Four eyes, as core reads `requireSeparateApprover` from the community: an edit then waits for a second approver. */
  setSeparateApprover(guildId: string, required: boolean) {
    if (required) this.separateApprover.add(guildId)
    else this.separateApprover.delete(guildId)
  }

  /** An existing policy; returns its id. Defaults: active, propose mode, weekly on Monday 18:00 UTC. */
  seed(guildId: string, over: Partial<PolicyDetail> & { name: string; instruction: string }, preview: PolicyPreview | null = null): string {
    const id = over.id ?? `pol_${++this.counter}`
    const now = this.clock.now()
    const detail: PolicyDetail = {
      id,
      status: 'active',
      mode: 'propose',
      schedule: { kind: 'weekly', weekday: 1, hour: 18, timezone: 'UTC' },
      version: 1,
      nextRunAt: null,
      matchesNow: preview ? preview.matches.length : null,
      ruleInWords: `Pays what "${over.name}" says.`,
      filter: { hasRole: [], messagesIn: null },
      vetoWindowMinutes: 24 * 60,
      caps: { perRun: null, perPerson: null },
      createdBy: '0',
      createdAt: now,
      approvedBy: null,
      approvedAt: null,
      pendingVersion: null,
      ...over,
    }
    if (detail.status === 'draft') detail.pendingVersion = detail.version
    const version: PolicyVersionView = {
      version: detail.version,
      instruction: detail.instruction,
      ruleInWords: detail.ruleInWords,
      filter: detail.filter,
      createdBy: detail.createdBy,
      createdAt: detail.createdAt,
      approvedBy: detail.approvedBy,
      approvedAt: detail.approvedAt,
      status: detail.status === 'draft' ? 'pending' : 'approved',
    }
    this.policies.set(`${guildId}:${id}`, { guildId, detail, versions: [version], preview })
    return id
  }

  setPreview(guildId: string, policyId: string, preview: PolicyPreview) {
    const p = this.policies.get(`${guildId}:${policyId}`)
    if (p) p.preview = preview
  }

  /** Marks a run as generated by a policy. */
  linkRun(guildId: string, runId: string, origin: RunOrigin) {
    this.origins.set(`${guildId}:${runId}`, origin)
  }

  addEvent(guildId: string, event: Omit<AuditEventView, 'id'> & { id?: string }) {
    this.stream.push({ ...event, id: event.id ?? `evt_${String(++this.counter).padStart(6, '0')}`, guildId })
  }

  // ---- PolicyPort --------------------------------------------------------------------------

  async list(input: { guildId: string }): Promise<PolicySummary[]> {
    return [...this.policies.values()]
      .filter((p) => p.guildId === input.guildId)
      .map(({ detail: d }) => ({ id: d.id, name: d.name, status: d.status, mode: d.mode, schedule: d.schedule, version: d.version, nextRunAt: d.nextRunAt, matchesNow: d.matchesNow }))
  }

  async get(input: Ref) {
    const p = this.find(input)
    return p ? ok(structuredClone(p.detail)) : fail('policy_not_found')
  }

  async preview(input: Ref) {
    const p = this.find(input)
    if (!p) return fail('policy_not_found')
    return p.preview ? ok(structuredClone(p.preview)) : fail('preview_unavailable', 'Discord could not be read just now.')
  }

  async versions(input: Ref) {
    return structuredClone(this.find(input)?.versions ?? [])
  }

  async upcoming(input: { guildId: string; limit: number }): Promise<ScheduledRunView[]> {
    return [...this.policies.values()]
      .filter((p) => p.guildId === input.guildId && p.detail.status === 'active' && p.detail.nextRunAt)
      .map((p) => ({ policyId: p.detail.id, policyName: p.detail.name, at: p.detail.nextRunAt as Date, mode: p.detail.mode }))
      .sort((a, b) => a.at.getTime() - b.at.getTime())
      .slice(0, input.limit)
  }

  async runOrigins(input: { guildId: string; runIds: string[] }) {
    const out: Record<string, RunOrigin> = {}
    for (const id of input.runIds) {
      const o = this.origins.get(`${input.guildId}:${id}`)
      if (o) out[id] = structuredClone(o)
    }
    return out
  }

  async create(input: { guildId: string; actor: PolicyActor; draft: PolicyDraft }) {
    this.calls.push({ method: 'create', guildId: input.guildId, actor: input.actor })
    if (!this.permitted(input.guildId, input.actor)) return fail('not_permitted')
    if (!this.scheduleAllowed(input.draft.schedule)) return fail('schedule_not_allowed', DAILY_REFUSED)
    if (/unclear/i.test(input.draft.instruction)) return fail('could_not_compile', 'The rule could not be compiled from that instruction.')
    const id = this.seed(input.guildId, {
      name: input.draft.name,
      instruction: input.draft.instruction,
      schedule: input.draft.schedule,
      status: 'draft',
      createdBy: input.actor.id,
      ruleInWords: `Compiled from: ${input.draft.instruction}`,
      filter: { compiledFrom: 'instruction', length: input.draft.instruction.length },
    })
    this.audit(input.guildId, 'policy.created', input.actor.id, id, `Created "${input.draft.name}" as a draft.`)
    return ok({ policyId: id })
  }

  async edit(input: Ref & { actor: PolicyActor; draft: PolicyDraft; mode?: PolicyMode; vetoWindowMinutes?: number }) {
    const p = this.action('edit', input)
    if (!p.ok) return p
    const d = p.value.detail
    if (d.status === 'archived') return fail('illegal_state')
    if (!this.scheduleAllowed(input.draft.schedule)) return fail('schedule_not_allowed', DAILY_REFUSED)
    // Like core: in force at once from the approver role (the only one that acts here) on a policy approved before, unless four eyes are on.
    const inForce = !this.separateApprover.has(input.guildId) && (d.status === 'active' || d.status === 'paused')
    if (!inForce && input.mode === 'autopilot') return fail('policy_not_approved')
    let vetoWindowMinutes = d.vetoWindowMinutes
    if (inForce && (input.mode !== undefined || input.vetoWindowMinutes !== undefined)) {
      vetoWindowMinutes = input.vetoWindowMinutes ?? d.vetoWindowMinutes
      if (!this.vetoWindowAllowed(vetoWindowMinutes)) return fail('invalid_veto_window')
    }
    if (/unclear/i.test(input.draft.instruction)) return fail('could_not_compile', 'The rule could not be compiled from that instruction.')
    const version = Math.max(...p.value.versions.map((v) => v.version)) + 1
    const now = this.clock.now()
    for (const v of p.value.versions) {
      if (v.status === 'pending') v.status = 'discarded'
      else if (inForce && v.status === 'approved') v.status = 'superseded'
    }
    const ruleInWords = `Compiled from: ${input.draft.instruction}`
    const filter = { compiledFrom: 'instruction', length: input.draft.instruction.length }
    const approval = inForce ? { approvedBy: input.actor.id, approvedAt: now } : { approvedBy: null, approvedAt: null }
    p.value.versions.push({ version, instruction: input.draft.instruction, ruleInWords, filter, createdBy: input.actor.id, createdAt: now, ...approval, status: inForce ? 'approved' : 'pending' })
    Object.assign(d, {
      name: input.draft.name,
      instruction: input.draft.instruction,
      schedule: input.draft.schedule,
      ruleInWords,
      filter,
      version,
      ...approval,
      // Like core: in force, it keeps running and its mode (unless the edit names one); otherwise the policy is the new draft (it stops running, autopilot goes off) until approved.
      ...(inForce ? { mode: input.mode ?? d.mode, vetoWindowMinutes, pendingVersion: null } : { status: 'draft', mode: 'propose', nextRunAt: null, pendingVersion: version }),
    })
    this.audit(input.guildId, 'policy.edited', input.actor.id, input.policyId, `Edited "${d.name}": version ${version} ${inForce ? 'is in force' : 'waits for approval'}.`)
    return ok({ version, inForce })
  }

  async approve(input: Ref & { actor: PolicyActor; version: number }) {
    const p = this.action('approve', input)
    if (!p.ok) return p
    const d = p.value.detail
    if (d.status !== 'draft') return fail('illegal_state')
    if (input.version !== d.version) return fail('version_mismatch')
    if (!this.scheduleAllowed(d.schedule)) return fail('schedule_not_allowed')
    const v = p.value.versions.find((x) => x.version === input.version)
    if (!v) return fail('illegal_state')
    for (const x of p.value.versions) if (x.status === 'approved') x.status = 'superseded'
    Object.assign(v, { status: 'approved', approvedBy: input.actor.id, approvedAt: this.clock.now() })
    Object.assign(d, { status: 'active', approvedBy: input.actor.id, approvedAt: this.clock.now(), pendingVersion: null, nextRunAt: new Date(this.clock.now().getTime() + 86_400_000) })
    this.audit(input.guildId, 'policy.approved', input.actor.id, input.policyId, `Approved version ${v.version} of "${d.name}".`)
    return ok(undefined)
  }

  async discard(input: Ref & { actor: PolicyActor; version: number }) {
    const p = this.action('discard', input)
    if (!p.ok) return p
    const d = p.value.detail
    if (d.status !== 'draft') return fail('illegal_state')
    if (input.version !== d.version) return fail('version_mismatch')
    const v = p.value.versions.find((x) => x.version === input.version)
    if (!v) return fail('illegal_state')
    v.status = 'discarded'
    // Like core: back to the last approved version, paused; a policy never approved is archived.
    const prior = p.value.versions.filter((x) => x.version < v.version && x.approvedBy !== null && x.status !== 'discarded').at(-1)
    if (prior) {
      prior.status = 'approved'
      Object.assign(d, {
        version: prior.version,
        instruction: prior.instruction,
        ruleInWords: prior.ruleInWords,
        filter: prior.filter,
        status: 'paused',
        approvedBy: prior.approvedBy,
        approvedAt: prior.approvedAt,
        pendingVersion: null,
      })
    } else {
      Object.assign(d, { status: 'archived', pendingVersion: null, nextRunAt: null })
    }
    this.audit(input.guildId, 'policy.discarded', input.actor.id, input.policyId, `Discarded version ${v.version} of "${d.name}".`)
    return ok(undefined)
  }

  async pause(input: Ref & { actor: PolicyActor }) {
    return this.move('pause', input, 'active', 'paused', 'policy.paused', 'Paused')
  }

  async resume(input: Ref & { actor: PolicyActor }) {
    return this.move('resume', input, 'paused', 'active', 'policy.resumed', 'Resumed')
  }

  async archive(input: Ref & { actor: PolicyActor }) {
    const p = this.action('archive', input)
    if (!p.ok) return p
    if (p.value.detail.status === 'archived') return fail('illegal_state')
    Object.assign(p.value.detail, { status: 'archived', mode: 'propose', nextRunAt: null, pendingVersion: null })
    this.audit(input.guildId, 'policy.archived', input.actor.id, input.policyId, `Archived "${p.value.detail.name}".`)
    return ok(undefined)
  }

  async setMode(input: Ref & { actor: PolicyActor; mode: PolicyMode; vetoWindowMinutes: number }) {
    const p = this.action('setMode', input)
    if (!p.ok) return p
    const d = p.value.detail
    if (d.status === 'archived') return fail('illegal_state')
    if (input.mode === 'autopilot' && (d.approvedBy === null || d.status === 'draft')) return fail('policy_not_approved')
    if (!this.vetoWindowAllowed(input.vetoWindowMinutes)) return fail('invalid_veto_window')
    Object.assign(d, { mode: input.mode, vetoWindowMinutes: input.vetoWindowMinutes })
    const words = input.mode === 'autopilot' ? `autopilot, veto window ${input.vetoWindowMinutes} minutes` : 'propose'
    this.audit(input.guildId, 'policy.mode_changed', input.actor.id, input.policyId, `Switched "${d.name}" to ${words}.`)
    return ok(undefined)
  }

  async veto(input: { guildId: string; runId: string; actor: PolicyActor }) {
    this.calls.push({ method: 'veto', guildId: input.guildId, actor: input.actor })
    if (!this.permitted(input.guildId, input.actor)) return fail('not_permitted')
    const o = this.origins.get(`${input.guildId}:${input.runId}`)
    if (!o) return fail('policy_run_not_found')
    if (!o.vetoable) return fail('illegal_state')
    Object.assign(o, { vetoable: false, vetoedBy: input.actor.id, vetoedAt: this.clock.now() })
    this.addEvent(input.guildId, { at: this.clock.now(), type: 'policy_run.vetoed', actorId: input.actor.id, policyId: o.policyId, runId: input.runId, summary: 'Vetoed the run.' })
    return ok(undefined)
  }

  // ---- AuditPort ---------------------------------------------------------------------------

  async events(q: AuditQuery): Promise<AuditEventView[]> {
    const newestFirst = this.stream
      .filter((e) => e.guildId === q.guildId)
      .filter((e) => !q.type || e.type === q.type)
      .filter((e) => !q.actorId || e.actorId === q.actorId)
      .filter((e) => !q.policyId || e.policyId === q.policyId)
      .sort((a, b) => b.at.getTime() - a.at.getTime() || (a.id < b.id ? 1 : -1))
    const start = q.beforeId ? newestFirst.findIndex((e) => e.id === q.beforeId) + 1 : 0
    if (q.beforeId && start === 0) return []
    return newestFirst.slice(start, start + q.limit).map(({ guildId: _g, ...e }) => structuredClone(e))
  }

  // ---- internals ---------------------------------------------------------------------------

  /** Like core: daily only with the demo controls. */
  private scheduleAllowed(s: PolicyDetail['schedule']) {
    return s.kind !== 'daily' || this.dailySchedules
  }

  /** Like core without the demo controls: an hour to 7 days. */
  private vetoWindowAllowed(minutes: number) {
    return Number.isInteger(minutes) && minutes >= MIN_VETO_MINUTES && minutes <= MAX_VETO_MINUTES
  }

  private find(ref: Ref) {
    return this.policies.get(`${ref.guildId}:${ref.policyId}`)
  }

  private permitted(guildId: string, actor: PolicyActor) {
    const role = this.approverRoles.get(guildId)
    return role === undefined || actor.roleIds.includes(role)
  }

  private action(method: string, input: Ref & { actor: PolicyActor }): Result<Stored, PolicyError> {
    this.calls.push({ method, guildId: input.guildId, policyId: input.policyId, actor: input.actor })
    if (!this.permitted(input.guildId, input.actor)) return fail('not_permitted')
    const p = this.find(input)
    return p ? ok(p) : fail('policy_not_found')
  }

  private move(method: string, input: Ref & { actor: PolicyActor }, from: string, to: 'active' | 'paused', type: string, verb: string) {
    const p = this.action(method, input)
    if (!p.ok) return p
    if (p.value.detail.status !== from) return fail('illegal_state')
    if (to === 'active' && !this.scheduleAllowed(p.value.detail.schedule)) return fail('schedule_not_allowed')
    p.value.detail.status = to
    this.audit(input.guildId, type, input.actor.id, input.policyId, `${verb} "${p.value.detail.name}".`)
    return ok(undefined)
  }

  private audit(guildId: string, type: string, actorId: string | null, policyId: string | null, summary: string) {
    this.addEvent(guildId, { at: this.clock.now(), type, actorId, policyId, runId: null, summary })
  }
}
