import type { Result } from '@rolepay/core'
import type {
  AuditEventView,
  AuditPort,
  AuditQuery,
  PolicyActor,
  PolicyDetail,
  PolicyDraft,
  PolicyError,
  PolicyMode,
  PolicyPort,
  PolicyPreview,
  PolicySummary,
  PolicyVersionView,
  RunOrigin,
  ScheduledRunView,
} from '../dashboard/policyPort.js'

type Stored = { guildId: string; detail: PolicyDetail; versions: PolicyVersionView[]; preview: PolicyPreview | null }
type Ref = { guildId: string; policyId: string }

const ok = <T>(value: T): Result<T, PolicyError> => ({ ok: true, value })
const fail = (code: string, message?: string): Result<never, PolicyError> => ({ ok: false, error: message ? { code, message } : { code } })

/**
 * The policy and audit ports in memory, for tests and the browser e2e, until the real policy
 * services are wired (see `policyPort.ts`). Behaves like core is specified to: the approver role
 * is re-checked from the actor's roles on every action (`not_permitted`), an instruction is
 * "compiled" once into a draft (an instruction containing "unclear" cannot be compiled), an edit
 * makes a new version that needs a new approval, and every action lands in the audit stream.
 * `calls` records every action with its actor.
 */
export class InMemoryPolicies implements PolicyPort, AuditPort {
  readonly eventTypes = [
    'policy.created',
    'policy.edited',
    'policy.approved',
    'policy.discarded',
    'policy.paused',
    'policy.resumed',
    'policy.mode_changed',
    'policy.archived',
    'run.generated',
    'run.vetoed',
    'run.approved',
    'run.executed',
    'run.failed',
  ] as const
  readonly calls: { method: string; guildId: string; policyId?: string; actor: PolicyActor }[] = []
  private readonly policies = new Map<string, Stored>()
  private readonly stream: (AuditEventView & { guildId: string })[] = []
  private readonly origins = new Map<string, RunOrigin>()
  private readonly approverRoles = new Map<string, string>()
  private counter = 0

  constructor(private readonly clock: { now(): Date } = { now: () => new Date() }) {}

  // ---- seeding (tests) ---------------------------------------------------------------------

  /** The role that may act in this guild, as core reads it from the community. */
  setApproverRole(guildId: string, roleId: string) {
    this.approverRoles.set(guildId, roleId)
  }

  /** An existing policy; returns its id. Defaults: active, propose mode, weekly on Monday 18:00 UTC. */
  seed(guildId: string, over: Partial<PolicyDetail> & { name: string; instruction: string }, preview: PolicyPreview | null = null): string {
    const id = over.id ?? `pol_${++this.counter}`
    const now = this.clock.now()
    const detail: PolicyDetail = {
      id,
      status: 'active',
      mode: 'propose',
      schedule: { kind: 'weekly', weekday: 1, hour: 18, timezone: 'UTC' },
      version: 1,
      nextRunAt: null,
      matchesNow: preview ? preview.matches.length : null,
      ruleInWords: `Pays what "${over.name}" says.`,
      filter: { hasRole: [], messagesIn: null },
      vetoWindowHours: 24,
      caps: { perRun: null, perPerson: null },
      createdBy: '0',
      createdAt: now,
      approvedBy: null,
      approvedAt: null,
      pendingVersion: null,
      ...over,
    }
    const version: PolicyVersionView = {
      version: detail.version,
      instruction: detail.instruction,
      ruleInWords: detail.ruleInWords,
      filter: detail.filter,
      createdBy: detail.createdBy,
      createdAt: detail.createdAt,
      approvedBy: detail.approvedBy,
      approvedAt: detail.approvedAt,
      status: detail.status === 'draft' ? 'pending' : 'approved',
    }
    this.policies.set(`${guildId}:${id}`, { guildId, detail, versions: [version], preview })
    return id
  }

  setPreview(guildId: string, policyId: string, preview: PolicyPreview) {
    const p = this.policies.get(`${guildId}:${policyId}`)
    if (p) p.preview = preview
  }

  /** Marks a run as generated by a policy. */
  linkRun(guildId: string, runId: string, origin: RunOrigin) {
    this.origins.set(`${guildId}:${runId}`, origin)
  }

  addEvent(guildId: string, event: Omit<AuditEventView, 'id'> & { id?: string }) {
    this.stream.push({ ...event, id: event.id ?? `evt_${String(++this.counter).padStart(6, '0')}`, guildId })
  }

  // ---- PolicyPort --------------------------------------------------------------------------

  async list(input: { guildId: string }): Promise<PolicySummary[]> {
    return [...this.policies.values()]
      .filter((p) => p.guildId === input.guildId)
      .map(({ detail: d }) => ({ id: d.id, name: d.name, status: d.status, mode: d.mode, schedule: d.schedule, version: d.version, nextRunAt: d.nextRunAt, matchesNow: d.matchesNow }))
  }

  async get(input: Ref) {
    const p = this.find(input)
    return p ? ok(structuredClone(p.detail)) : fail('policy_not_found')
  }

  async preview(input: Ref) {
    const p = this.find(input)
    if (!p) return fail('policy_not_found')
    return p.preview ? ok(structuredClone(p.preview)) : fail('preview_unavailable', 'Discord could not be read just now.')
  }

  async versions(input: Ref) {
    return structuredClone(this.find(input)?.versions ?? [])
  }

  async upcoming(input: { guildId: string; limit: number }): Promise<ScheduledRunView[]> {
    return [...this.policies.values()]
      .filter((p) => p.guildId === input.guildId && p.detail.status === 'active' && p.detail.nextRunAt)
      .map((p) => ({ policyId: p.detail.id, policyName: p.detail.name, at: p.detail.nextRunAt as Date, mode: p.detail.mode }))
      .sort((a, b) => a.at.getTime() - b.at.getTime())
      .slice(0, input.limit)
  }

  async runOrigins(input: { guildId: string; runIds: string[] }) {
    const out: Record<string, RunOrigin> = {}
    for (const id of input.runIds) {
      const o = this.origins.get(`${input.guildId}:${id}`)
      if (o) out[id] = structuredClone(o)
    }
    return out
  }

  async create(input: { guildId: string; actor: PolicyActor; draft: PolicyDraft }) {
    this.calls.push({ method: 'create', guildId: input.guildId, actor: input.actor })
    if (!this.permitted(input.guildId, input.actor)) return fail('not_permitted')
    if (/unclear/i.test(input.draft.instruction)) return fail('could_not_compile', 'The rule could not be compiled from that instruction.')
    const id = this.seed(input.guildId, {
      name: input.draft.name,
      instruction: input.draft.instruction,
      schedule: input.draft.schedule,
      status: 'draft',
      createdBy: input.actor.id,
      ruleInWords: `Compiled from: ${input.draft.instruction}`,
      filter: { compiledFrom: 'instruction', length: input.draft.instruction.length },
      pendingVersion: 1,
    })
    this.audit(input.guildId, 'policy.created', input.actor.id, id, `Created "${input.draft.name}" as a draft.`)
    return ok({ policyId: id })
  }

  async edit(input: Ref & { actor: PolicyActor; draft: PolicyDraft }) {
    const p = this.action('edit', input)
    if (!p.ok) return p
    if (p.value.detail.status === 'archived') return fail('illegal_state')
    if (/unclear/i.test(input.draft.instruction)) return fail('could_not_compile', 'The rule could not be compiled from that instruction.')
    const version = Math.max(...p.value.versions.map((v) => v.version)) + 1
    for (const v of p.value.versions) if (v.status === 'pending') v.status = 'discarded'
    p.value.versions.push({
      version,
      instruction: input.draft.instruction,
      ruleInWords: `Compiled from: ${input.draft.instruction}`,
      filter: { compiledFrom: 'instruction', length: input.draft.instruction.length },
      createdBy: input.actor.id,
      createdAt: this.clock.now(),
      approvedBy: null,
      approvedAt: null,
      status: 'pending',
    })
    p.value.detail.pendingVersion = version
    this.audit(input.guildId, 'policy.edited', input.actor.id, input.policyId, `Edited "${p.value.detail.name}": version ${version} waits for approval.`)
    return ok({ version })
  }

  async approve(input: Ref & { actor: PolicyActor; version: number }) {
    const p = this.action('approve', input)
    if (!p.ok) return p
    const v = p.value.versions.find((x) => x.version === input.version && x.status === 'pending')
    if (!v) return fail('illegal_state')
    for (const x of p.value.versions) if (x.status === 'approved') x.status = 'superseded'
    Object.assign(v, { status: 'approved', approvedBy: input.actor.id, approvedAt: this.clock.now() })
    Object.assign(p.value.detail, {
      status: p.value.detail.status === 'draft' ? 'active' : p.value.detail.status,
      version: v.version,
      instruction: v.instruction,
      ruleInWords: v.ruleInWords,
      filter: v.filter,
      approvedBy: input.actor.id,
      approvedAt: this.clock.now(),
      pendingVersion: null,
      nextRunAt: p.value.detail.nextRunAt ?? new Date(this.clock.now().getTime() + 86_400_000),
    })
    this.audit(input.guildId, 'policy.approved', input.actor.id, input.policyId, `Approved version ${v.version} of "${p.value.detail.name}".`)
    return ok(undefined)
  }

  async discard(input: Ref & { actor: PolicyActor; version: number }) {
    const p = this.action('discard', input)
    if (!p.ok) return p
    const v = p.value.versions.find((x) => x.version === input.version && x.status === 'pending')
    if (!v) return fail('illegal_state')
    v.status = 'discarded'
    p.value.detail.pendingVersion = null
    if (p.value.detail.status === 'draft') p.value.detail.status = 'archived'
    this.audit(input.guildId, 'policy.discarded', input.actor.id, input.policyId, `Discarded version ${v.version} of "${p.value.detail.name}".`)
    return ok(undefined)
  }

  async pause(input: Ref & { actor: PolicyActor }) {
    return this.move('pause', input, 'active', 'paused', 'policy.paused', 'Paused')
  }

  async resume(input: Ref & { actor: PolicyActor }) {
    return this.move('resume', input, 'paused', 'active', 'policy.resumed', 'Resumed')
  }

  async archive(input: Ref & { actor: PolicyActor }) {
    const p = this.action('archive', input)
    if (!p.ok) return p
    if (p.value.detail.status === 'archived') return fail('illegal_state')
    Object.assign(p.value.detail, { status: 'archived', nextRunAt: null, pendingVersion: null })
    this.audit(input.guildId, 'policy.archived', input.actor.id, input.policyId, `Archived "${p.value.detail.name}".`)
    return ok(undefined)
  }

  async setMode(input: Ref & { actor: PolicyActor; mode: PolicyMode; vetoWindowHours: number }) {
    const p = this.action('setMode', input)
    if (!p.ok) return p
    if (input.vetoWindowHours < 1) return fail('invalid_input', 'The veto window is at least 1 hour.')
    Object.assign(p.value.detail, { mode: input.mode, vetoWindowHours: input.vetoWindowHours })
    const words = input.mode === 'autopilot' ? `autopilot, veto window ${input.vetoWindowHours} h` : 'propose'
    this.audit(input.guildId, 'policy.mode_changed', input.actor.id, input.policyId, `Switched "${p.value.detail.name}" to ${words}.`)
    return ok(undefined)
  }

  // ---- AuditPort ---------------------------------------------------------------------------

  async events(q: AuditQuery): Promise<AuditEventView[]> {
    const newestFirst = this.stream
      .filter((e) => e.guildId === q.guildId)
      .filter((e) => !q.type || e.type === q.type)
      .filter((e) => !q.actorId || e.actorId === q.actorId)
      .filter((e) => !q.policyId || e.policyId === q.policyId)
      .sort((a, b) => b.at.getTime() - a.at.getTime() || (a.id < b.id ? 1 : -1))
    const start = q.beforeId ? newestFirst.findIndex((e) => e.id === q.beforeId) + 1 : 0
    if (q.beforeId && start === 0) return []
    return newestFirst.slice(start, start + q.limit).map(({ guildId: _g, ...e }) => structuredClone(e))
  }

  // ---- internals ---------------------------------------------------------------------------

  private find(ref: Ref) {
    return this.policies.get(`${ref.guildId}:${ref.policyId}`)
  }

  private permitted(guildId: string, actor: PolicyActor) {
    const role = this.approverRoles.get(guildId)
    return role === undefined || actor.roleIds.includes(role)
  }

  private action(method: string, input: Ref & { actor: PolicyActor }): Result<Stored, PolicyError> {
    this.calls.push({ method, guildId: input.guildId, policyId: input.policyId, actor: input.actor })
    if (!this.permitted(input.guildId, input.actor)) return fail('not_permitted')
    const p = this.find(input)
    return p ? ok(p) : fail('policy_not_found')
  }

  private move(method: string, input: Ref & { actor: PolicyActor }, from: string, to: 'active' | 'paused', type: string, verb: string) {
    const p = this.action(method, input)
    if (!p.ok) return p
    if (p.value.detail.status !== from) return fail('illegal_state')
    p.value.detail.status = to
    this.audit(input.guildId, type, input.actor.id, input.policyId, `${verb} "${p.value.detail.name}".`)
    return ok(undefined)
  }

  private audit(guildId: string, type: string, actorId: string | null, policyId: string | null, summary: string) {
    this.addEvent(guildId, { at: this.clock.now(), type, actorId, policyId, runId: null, summary })
  }
}
